version: '2'

services:
  db:
    build: mysql
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  php-apache:
    build: php7-apache
    ports:
      - '80:80'
      - '8000:8000'
    volumes:
      - ${APP_PATH}:/var/www
